# Generated by Django 4.2.7 on 2023-11-09 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="liked_at",
            new_name="liked_on",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created_on",
        ),
    ]
