# Generated by Django 4.2.7 on 2023-11-10 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_post_highlighted_post_language_post_linenos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="highlighted",
        ),
    ]
