# Generated by Django 4.2.7 on 2023-11-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_remove_post_highlighted"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="highlighted",
            field=models.TextField(default="highlighted"),
            preserve_default=False,
        ),
    ]
