# Generated by Django 4.2.7 on 2023-11-10 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0006_post_highlighted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="highlighted",
        ),
    ]
