# Generated by Django 4.2.7 on 2023-11-10 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0008_rename_author_post_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="language",
        ),
        migrations.RemoveField(
            model_name="post",
            name="linenos",
        ),
        migrations.RemoveField(
            model_name="post",
            name="style",
        ),
    ]
