# Generated by Django 4.2.7 on 2023-11-10 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0010_rename_post_like_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="owner",
            new_name="post",
        ),
    ]
